env:
  node:     true
  browser:  true

parserOptions:
  ecmaVersion: 5
  sourceType: script

globals:
  Promise:  true

ignorePatterns:
  - test/fixtures/

rules:
  camelcase: 0
  key-spacing: 0
  no-multi-spaces: 0
  padded-blocks: 0
  no-var: 0
  no-multiple-empty-lines: 0
